### PR TITLE
CarpetX: Merge documentation files into a single .tex file

### PR DESCRIPTION
**Pull request by lucass-carneiro**
The documentation used to be split into multiple `.tex` files, for organization.
This PR merges them into a single `documentation.tex` file.

This is necessary for the automated build scripts for the online ETK Thorn Documentation pages to work.

### CODE REVIEW

**Comment by rhaas80** [comment]
Probably should update the commit message to be active mode and present tense. Prefix commit messages by the string "Carpet: " (without the quotes, with the space at the end) so that one can more easily tell which thorn (more than one in the repo) is affected by the commit.   
  
I am assuming that the change is really just replacing the `\input{foo.tex}` lines by the content of `foo.tex`? I tried on my workstation and (barring unrelated errors) I can actually build the HTML thorndoc for CarpetX.

**Comment by lucass-carneiro** [comment]
I Have amended the message in the last commit, but it does not seem to be reflecting The changes in the PR page. Would you like me to send a new PR?

As far as changes go, yes, The change is really just replacing `\input{foo.tex}` by the contents of `foo.tex`

**Comment by rhaas80** [comment]
your most likely need to force-push into your pull request branch on github (a regular "git push" should show an error message after a "git commit --amend").

**Comment by rhaas80** [comment]
oh and of course I have a typo. the thorn is "CarpetX: " not "Carpet: " :-)

**Review by eschnett — CHANGES_REQUESTED** [review]
@lucass-carneiro You will need to resolve the conflicts before this can be merged.

**Comment by lucass-carneiro** [comment]
@eschnett I believe I have resolved all conflicts.

**Review by eschnett — APPROVED** [review]

**Pull request merged**
