### PR TITLE
Algo: declare dependency on Loop

### PR DESCRIPTION
**Pull request by rhaas80**
and thus CarpetX and thus AMReX

### CODE REVIEW

**Comment by eschnett** [comment]
I don't think that `Algo` depends on `Loops`. It doesn't include `loop.hxx`, nor does it contain loops over grid functions.

**Comment by lwJi** [comment]
It does. since `CCTK_HOST` and `CCTK_DEVICE` are defined there

**Comment by eschnett** [comment]
`Loop` is a heavy dependency. I would rather not have it just for some macros.

We can define these macros elsewhere, e.g. in `defs.hxx` of `Arith`. For example, `Arith` already defines `ARITH_DEVICE` etc., and we could extend this to define `CCTK_DEVICE` as well. Or we move these definitions to the flesh. Or we define `ALGO_DEVICE` locally.

**Comment by rhaas80** [comment]
Well I did not do a very careful check where the dependency comes from. The error message produced was:  
\`\`\`  
In file included from /data/rhaas/postdoc/gr/cactus/CarpetX\_SPIN/configs/sim/bindings/include/loop.hxx: ,  
                 from /data/rhaas/postdoc/gr/cactus/CarpetX\_SPIN/arrangements/CarpetX/Algo/src/roots.hxx:4,  
                 from /data/rhaas/postdoc/gr/cactus/CarpetX\_SPIN/configs/sim/build/Algo/roots.cxx:1:  
/data/rhaas/postdoc/gr/cactus/CarpetX\_SPIN/arrangements/CarpetX/Loop/src/loop.hxx:4:10: fatal error: AMReX\_FArrayBox.H: No such file or directory  
    4 | #include \<AMReX\_FArrayBox.H>  
\`\`\`  
which I took to mean that Alog's `root.cxx` includes `loop.hxx` and thus added the `Lopp` dependency. I agree that this would be quite a heavy dependency for Algo, which would otherwise not be dependent on a mesh and implement generic algorithms.

**Comment by eschnett** [comment]
I see. The test cases are calling into AMReX, and thus the thorn needs to depend on the `AMReX` capability. In an ideal world the test cases could be moved to a separate thorn, but I doubt anyone will use Algo without AMReX in the foreseeable future.

Can we remove the dependency on `loop.hxx` in `roots.hxx` instead?

We should also add the missing include statement to `roots.cxx` to define the respective AMReX functions.

**Comment by lwJi** [comment]
Sure. How about define `ALGO_DEVICE` locally then?

**Comment by eschnett** [comment]
I suggest https://github.com/eschnett/CarpetX/pull/141 instead of this pull request. This adds a dependency on AMReX and defines `ALGO_DEVICE` etc. until respective flesh definitions become available.

**Comment by rhaas80** [comment]
sure. I took a look and approved it.

**Pull request closed without merging**
