### PR TITLE
Derivs: Increase imax by the stencil radius in mask for derivatives

### PR DESCRIPTION
**Pull request by lwJi**

### CODE REVIEW

**Comment by eschnett** [comment]
Can you add some comments to the code?

**Comment by lwJi** [comment]
I have added some comments for `mask1`

**Comment by eschnett** [comment]
Are you using these methods for a physics thorn? If so, can you add a test case there so that this thorn won't break in the future?

**Comment by lwJi** [comment]
I have a thorn `TestDerivs` that I haven't pushed it. I will pushed it when everything works and add a unit test to it. The physics thorn is still using their own `derivs.hxx` for the moment. I will try to modify them to call the functions from `Derivs/src/derivs.hxx` when I'm pretty sure everything is working here.

**Comment by eschnett** [comment]
You could add the test thorn to this pull request, and also modify `scripts/carpetx.th` to include `TestDerivs` so that it gets tested as well.

**Comment by lwJi** [comment]
I will do that

**Pull request merged**
